apiVersion: apps/v1
kind: Deployment
metadata:
  name: vss-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vss
  template:
    metadata:
      labels:
        app: vss
    spec:
      containers:
        - name: vss-container
          image: myacr.azurecr.io/vss-app:latest  # Replace with your ACR image
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"


apiVersion: v1
kind: Service
metadata:
  name: vss-service
spec:
  selector:
    app: vss
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
